version: '3'
services:
  bot-server:
    build:
      context: ./packages/bot
    environment:
      MICROSOFT_APP_ID: ""
      MICROSOFT_APP_PASSWORD: ""
    image: bot-server:latest
    depends_on:
    - bot-emulator
  bot-emulator:
    build:
      context: ./packages/emulator
    environment:
      MICROSOFT_APP_ID: ""
      MICROSOFT_APP_PASSWORD: ""
    image: bot-emulator:latest
    ports:
    - "5000:5000"
  web-server:
    build:
      context: ./packages/web
    image: web-server:latest
    ports:
    - "3000:80"
